### ISSUE TITLE
33. display: none; 与 visibility: hidden; 的区别

### ISSUE THREAD

**Issue by Tyh2001** [Tyh2001/Web-interview-Lssuse#33]
> 相同点：都是让元素不可见

区别：

- display: none; 会让元素从状态树中消失，渲染不会站位任何空间
- visibility: hidden; 不会让元素从状态树中消失，渲染元素会继续占据空间

> 简答一句话就是：
>
> display: none; 隐藏后不占位
>
> visibility: hidden; 隐藏后仍占占位

- display: none; 是非继承属性，⼦孙节点消失由于元素从渲染树消失造成，通过修改

  子孙节点属性无法显示 

- visibility: hidden; 是继承属性，子孙节点消失由于继承 了 hidden ，通过设置 visibility: visible; 可以让子孙节点显式 

> 简单一句话就是：
>
> 设置 display: none; 的子孙元素都不能再显示
>
> 设置 visibility: hidden;  的子孙元素可以通过给子孙元素设置 visibility: visible; 进行显示

代码演示：

```css
.box {
    width: 300px;
    height: 300px;
    background: red;
    display: none;
}
.box2 {
    width: 100px;
    height: 100px;
    background: green;
    /* display: block; */
    /* visibility: hidden; */
}
```

```html
<div class="box">
    <div class="box2"></div>
</div>
```

当 box 设置了：`display: none;` 只后，那么给 box2 设置 `display: block;`还是 `visibility: hidden;`，都不能让 box2显示

那么要是这样的样式：

```css
.box {
    width: 300px;
    height: 300px;
    background: red;
    visibility: hidden;
}
.box2 {
    width: 100px;
    height: 100px;
    background: green;
    visibility: visible;
}
```

当 box 设置了：`visibility: hidden;` 只后，那么只要给 box2 设置 `visibility: visible;`即可让 box2 显示
