### ISSUE TITLE
36. 如何创建块级格式化上下文，BFC有什么用？

### ISSUE THREAD

**Issue by Tyh2001** [Tyh2001/Web-interview-Lssuse#36]
> 块级格式化上下文 是什么？
>
> 块格式上下文即为：Block formatting context（简称 BFC）
>
> 块格式上下文是布局过程中生成块级盒子的区域，也是浮动元素与其他元素的交互限定区域。
>
> BFC 是一个独立的区域，让 BFC 内部的元素与外部的元素相互隔离
>
> 也就是内外元素互不影响

- BFC 如何创建（如何创建块级格式化上下文）

**一、触发条件：**

1. 定位触发：

通过 `position: fixed;` 和 `position: absolute;` 属性可以触发

> 注：`position: relative;` 不会触发！

2. display 触发

通过 `display: inline-block;` 和 `display: table;` 属性可以触发

3. overflow 触发

overflow 的值只要不是 `visible` 都可以触发

例如：`overflow: hidden;` 、 `overflow: auto;` 等等

**二、规则**

1. 属于同一个 BFC 的两个相邻的盒子（垂直排列）
2. 属于同一个 BFC 的两个相邻盒子的 margin 会发生重叠
3. BFC 的区域不会 与 float 的元素区域发生重叠
4. 文字不会被浮动覆盖，会环绕与周围
5. BFC 中的子元素 的 margin 不会合并与父级的外边距重叠
6. 计算 BFC 高度的时候 浮动元素也会参与计算

- 应用

1. 阻止外边距重叠
2. 阻止元素被浮动元素覆盖（清除浮动）
3. 自适应的两栏布局
4. 可以解决高度塌陷（清除内部元素浮动）

实例：

```html
<div class="box">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
    <div class="item">4</div>
</div>
```

```css
.box {
    background: skyblue;
}

.box .item {
    width: 100px;
    border: 2px solid black;
    float: left;
}
```

当 box 没有设置高度时，里面的元素浮动，就会造成父级的盒子塌陷，那么 box 的背景色也就看不到了

解决方式：通过给父级元素设置 BFC 容器，即可解决

可以通过下面任意一条属性解决

```css
.box {
    background: skyblue;
    position: fixed;
    /* position: absolute; */
    /* display: inline-block; */
    /* display: table; */
    /* overflow: hidden; */
    /* overflow: auto; */
}
```
