### ISSUE TITLE
47. display:inline-block 什么时候不会显示间隙？

### ISSUE THREAD

**Issue by Tyh2001** [Tyh2001/Web-interview-Lssuse#47]
当两个盒子都设置 `display:inline-block;` 之后，两个盒子中间会有个间隙代码如下：

```css
* {
    margin: 0;
    padding: 0;
}
.box1 {
    width: 200px;
    height: 300px;
    background: red;
    display:inline-block;
}
.box2 {
    width: 200px;
    height: 300px;
    background: blue;
    display:inline-block;
}
```

```html
<div class="box">
    <div class="box1"></div>
    <div class="box2"></div>
</div>
```

解决方式：

- 使用 *font-size*: 0;

```css
.box {
    font-size: 0px;
}
```

- 使用 margin 负值

```css
.box2 {
    width: 200px;
    height: 300px;
    background: blue;
    display: inline-block;
    margin-left: -5px;
}
```

- 使用 letter-spacing （设置元素间距）

```css
.box {
    letter-spacing: -5px;
}

.box1 {
    width: 200px;
    height: 300px;
    background: red;
    display: inline-block;
}

.box2 {
    width: 200px;
    height: 300px;
    background: blue;
    display: inline-block;
}
```

```html
<div class="box">
    <div class="box1"></div>
    <div class="box2"></div>
</div>
```

- word-spacing 属性（设置指定元素之间的空间）

> 和上面 `letter-spacing` 用法类似
