### ISSUE TITLE
51. ::before 和 :after中双冒号和单冒号有什么区别？解释⼀下这2个伪元素的作用

### ISSUE THREAD

**Issue by Tyh2001** [Tyh2001/Web-interview-Lssuse#51]
- 单冒号( : )⽤于 CSS3 伪类，双冒号( :: )⽤于 CSS3 伪元素

:before 和 :after ：在元素之前和之后插入内容

```html
<p id="text">这是一段文字</p>
```

```css
#text:before {
    content: "你好啊";
    display: block;
    background: skyblue;
}
#text:after {
    content: "你是谁";
    display: block;
    background: green;
}
```

- 效果的一样的，仅用于区分伪类和伪元素
